# Generated by Django 4.2.5 on 2023-09-14 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_scripts'),
        ('cast', '0004_remove_person_scripts'),
        ('reviews', '0002_alter_reviews_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(default='', max_length=20000)),
                ('content_type', models.CharField(choices=[(1, 'Movie'), (2, 'Actor'), (3, 'Character'), (4, 'Cast')], default=1, max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.character')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cast.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
