# Generated by Django 4.2.5 on 2023-09-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content_type',
            field=models.IntegerField(choices=[(1, 'movie'), (2, 'actor'), (3, 'character'), (4, 'cast')], default=1),
        ),
    ]
