# Generated by Django 4.2.5 on 2023-09-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0006_remove_review_content_type_remove_review_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='character',
        ),
        migrations.RemoveField(
            model_name='review',
            name='person',
        ),
        migrations.AlterField(
            model_name='review',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
    ]
