# Generated by Django 4.2.5 on 2023-09-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_review_character_remove_review_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='object_type',
            new_name='content_type',
        ),
    ]
