# Generated by Django 4.2.5 on 2023-09-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_scripts'),
        ('reviews', '0009_alter_review_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='review',
            name='object_id',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie'),
        ),
    ]
