# Generated by Django 4.2.5 on 2023-09-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_scripts'),
        ('reviews', '0010_remove_review_content_type_remove_review_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='movies.movie'),
        ),
    ]
