# Generated by Django 4.2.5 on 2023-09-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', verbose_name=20)),
                ('lastName', models.CharField(default='', verbose_name=20)),
                ('biography', models.CharField(default='', verbose_name=20000)),
            ],
        ),
    ]
