# Generated by Django 4.2.5 on 2023-09-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_character_movie'),
        ('cast', '0002_person_scripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='scripts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scripts', to='movies.movie'),
        ),
    ]
