# Generated by Django 4.2.5 on 2023-09-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0003_alter_person_scripts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='scripts',
        ),
    ]
