# Generated by Django 4.2.5 on 2023-09-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', verbose_name=50)),
                ('description', models.CharField(default='', verbose_name=20000)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.person')),
            ],
        ),
    ]
