# Generated by Django 4.2.5 on 2023-09-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0001_initial'),
        ('movies', '0002_remove_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cast.person'),
        ),
        migrations.AlterField(
            model_name='character',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actors', to='movies.movie'),
        ),
    ]
