# Generated by Django 4.2.5 on 2023-09-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='movie',
        ),
    ]
