# Generated by Django 4.2.5 on 2023-09-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_character_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='actors', to='movies.movie'),
        ),
    ]
