# Generated by Django 4.2.5 on 2023-09-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_character_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='scripts',
            field=models.JSONField(default=None),
        ),
    ]
